load("@bazel_tools//tools/build_defs/repo:java.bzl", "java_import_external")

java_import_external(
    name = "com_google_auto_common",
    jar_sha256 = "eee75e0d1b1b8f31584dcbe25e7c30752545001b46673d007d468d75cf6b2c52",
    jar_urls = [
        "http://domain-registry-maven.storage.googleapis.com/repo1.maven.org/maven2/com/google/auto/auto-common/0.7/auto-common-0.7.jar",
        "http://repo1.maven.org/maven2/com/google/auto/auto-common/0.7/auto-common-0.7.jar",
    ],
    licenses = ["notice"],  # Apache 2.0
    deps = ["@com_google_guava"],
)

java_import_external(
    name = "com_google_auto_value",
    extra_build_file_content = "\n".join([
        "java_plugin(",
        "    name = \"AutoAnnotationProcessor\",",
        "    output_licenses = [\"unencumbered\"],",
        "    processor_class = \"com.google.auto.value.processor.AutoAnnotationProcessor\",",
        "    tags = [\"annotation=com.google.auto.value.AutoAnnotation;genclass=${package}.AutoAnnotation_${outerclasses}${classname}_${methodname}\"],",
        "    deps = [\":processor\"],",
        ")",
        "",
        "java_plugin(",
        "    name = \"AutoValueProcessor\",",
        "    output_licenses = [\"unencumbered\"],",
        "    processor_class = \"com.google.auto.value.processor.AutoValueProcessor\",",
        "    tags = [\"annotation=com.google.auto.value.AutoValue;genclass=${package}.AutoValue_${outerclasses}${classname}\"],",
        "    deps = [\":processor\"],",
        ")",
        "",
        "java_library(",
        "    name = \"com_google_auto_value\",",
        "    exported_plugins = [",
        "        \":AutoAnnotationProcessor\",",
        "        \":AutoValueProcessor\",",
        "    ],",
        "    exports = [",
        "        \":compile\",",
        "        \"@com_google_code_findbugs_jsr305\",",
        "    ],",
        ")",
    ]),
    generated_linkable_rule_name = "processor",
    generated_rule_name = "compile",
    jar_sha256 = "ea26f99150825f61752efc8784739cf50dd25d7956774573f8cdc3b948b23086",
    jar_urls = [
        "http://domain-registry-maven.storage.googleapis.com/repo1.maven.org/maven2/com/google/auto/value/auto-value/1.4-rc2/auto-value-1.4-rc2.jar",
        "http://repo1.maven.org/maven2/com/google/auto/value/auto-value/1.4-rc2/auto-value-1.4-rc2.jar",
    ],
    licenses = ["notice"],  # Apache 2.0
    neverlink = True,
    deps = [
        "@com_google_auto_common",
        "@com_google_code_findbugs_jsr305",
        "@com_google_guava",
    ],
)

java_import_external(
    name = "com_google_guava",
    jar_sha256 = "a42edc9cab792e39fe39bb94f3fca655ed157ff87a8af78e1d6ba5b07c4a00ab",
    jar_urls = [
        "https://repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar",
    ],
    licenses = ["notice"],  # The Apache Software License, Version 2.0
    exports = [
        "@com_google_code_findbugs_jsr305",
        "@com_google_errorprone_error_prone_annotations",
    ],
)

java_import_external(
    name = "com_google_code_findbugs_jsr305",
    jar_sha256 = "905721a0eea90a81534abb7ee6ef4ea2e5e645fa1def0a5cd88402df1b46c9ed",
    jar_urls = [
        "http://domain-registry-maven.storage.googleapis.com/repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar",
        "http://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar",
    ],
    licenses = ["notice"],  # The Apache Software License, Version 2.0
)

java_import_external(
    name = "com_google_errorprone_error_prone_annotations",
    jar_sha256 = "e7749ffdf03fb8ebe08a727ea205acb301c8791da837fee211b99b04f9d79c46",
    jar_urls = [
        "http://domain-registry-maven.storage.googleapis.com/repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.0.15/error_prone_annotations-2.0.15.jar",
        "http://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.0.15/error_prone_annotations-2.0.15.jar",
    ],
    licenses = ["notice"],  # Apache 2.0
)

java_import_external(
    name = "javax_inject",
    jar_sha256 = "91c77044a50c481636c32d916fd89c9118a72195390452c81065080f957de7ff",
    jar_urls = [
        "http://domain-registry-maven.storage.googleapis.com/repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar",
        "http://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar",
    ],
    licenses = ["notice"],  # The Apache Software License, Version 2.0
)

java_import_external(
    name = "junit",
    jar_sha256 = "8e495b634469d64fb8acfa3495a065cbacc8a0fff55ce1e31007be4c16dc57d3",
    jar_urls = [
        "https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar",
    ],
    licenses = ["notice"]
)

java_import_external(
    name = "com_google_truth",
    jar_sha256 = "fc0b67782289a2aabfddfdf99eff1dcd5edc890d49143fcd489214b107b8f4f3",
    jar_urls = [
        "https://repo1.maven.org/maven2/com/google/truth/truth/1.1.3/truth-1.1.3.jar",
    ],
    licenses = ["notice"]
)

java_import_external(
    name = "com_google_truth_java8",
    jar_sha256 = "2bbd32dd2fa9470d17f1bbda4f52b33b60bce4574052c1d46610a0aa371fc446",
    jar_urls = [
        "https://repo1.maven.org/maven2/com/google/truth/extensions/truth-java8-extension/1.1.3/truth-java8-extension-1.1.3.jar",
    ],
    licenses = ["notice"],
)