java_library(
    name = "Edge",
    srcs = ["Edge.java"],
    deps = [
        "@com_google_auto_value",
    ],
)

java_library(
    name = "Graph",
    srcs = ["Graph.java"],
    deps = [
        ":Edge",
        "@com_google_auto_value",
        "@com_google_guava",
    ],
)
