def run(command)
    puts(command)
    system(command)
end

task :build do
    command = [
        "bazel build",
        "//:main",
        "//:load_input",
        "//:graph",
        "//:binary_heap",
        "//:dijkstra",
    ].join(" ")
    run(command)
end

task :run => [:build] do
    command = [
        "bazel-bin/main",
        "../data/00.in.txt",
        "../temp/00.out.txt",
        "--stderrthreshold=0",
    ].join(" ")
    run(command)
end

task :test do
    command = [
        "bazel test",
        "--test_output=all",
        "//:graph_test",
        "//:binary_heap_test",
    ].join(" ")
    run(command)
end

task :refresh do
    run("rm external")
    command = [
        "bazel run",
        "@hedron_compile_commands//:refresh_all",
    ].join(" ")
    run(command)
end