java_test(
    name = "GraphTest",
    srcs = ["GraphTest.java"],
    deps = [
        "//java/dijkstra:Edge",
        "//java/dijkstra:Graph",
        "@com_google_guava",
        "@com_google_truth",
        "@com_google_truth_java8",
        "@junit",
    ],
)
